version: '3.8'
services:
  backend:
    build:
      context: ../backend  # Pfad zum Backend-Verzeichnis
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
