version: '3.9'

services:
  keycloak:
    container_name: keycloak_dev
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/imports/realm-export.json
      - KC_LOGLEVEL=DEBUG
    volumes:
      - ./import/:/opt/keycloak/data/import:ro
      - ./themes/custom-theme:/opt/keycloak/themes/custom-theme
    entrypoint:
      [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth" ]
      interval: 300s
      timeout: 10s
      retries: 5
