name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - 'feature/**'  # Alle Branches, die mit 'feature/' beginnen

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Neueste Version des Checkout-Action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Neueste Version von Docker Buildx Setup

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Neueste Version für Docker Login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Backend Docker image
        working-directory: ./backend  # Pfad zu deinem Backend-Verzeichnis
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push Frontend Docker image
        working-directory: ./frontend  # Pfad zu deinem Frontend-Verzeichnis
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest